project:
  type: website
  output-dir: docs

website:
  favicon: logo.png
  twitter-card: true
  title: "Evidence House"
  open-graph: true
  navbar:
    logo: "logo.png"
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: newsletters.qmd
        text: News
      - href: workshops.qmd
        text: Workshops
      - playbook/playbook.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/evidence_house
      - icon: linkedin
        href: https://www.linkedin.com/company/evidence-house/
      - icon: github
        href: https://github.com/no10ds/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



