---
title: "Data Access Guide"
---

### AWS CLI

To access the Hackathon data, you will need to download and install the AWS CLI tool. You can find instructions for this [here](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html)

To verify the AWS CLI has installed properly you can run:

```
$ aws --version
```

Which should return something like:

`aws-cli/2.10.0 Python/3.11.2 Darwin/18.7.0 botocore/2.4.5`

You might need to restart your terminal for the AWS CLI to be available.

---

### Hackathon Data

The data for the hackathon can be downloaded from AWS using the command:

```
aws s3 cp s3://evidence-house-hackathon-27-07-23 <YOUR_FOLDER> --recursive --no-sign-request
```

The full dataset is approximately `3GB` and might take a few minutes to download.

To just download one of the data folders e.g. `civil-service-jobs` you can run:

```
aws s3 cp s3://evidence-house-hackathon-27-07-23/civil-service-jobs/ . --recursive --no-sign-request
```

This will download the Civil Service Jobs data to your current directory.

The dataset options are:

- civil-service-jobs
- customer_service
- emergency-alert
- fcdo-evaluations
- heat-wave
- pac-correspondence
- parliament-bills

---

The files come in a variety of formats:

- OpenOffice Documents
- PDFs
- Excel Spreadsheets
- CSVs
- HTML documents

If you are using `Python` to operate on the data you might find the [`odfpy`](https://pypi.org/project/odfpy/) module helpful for reading OpenOffice documents.

If ypu are using `R` you might find the [`readODS`](https://rdrr.io/cran/readODS/) or [`trinker/textreadr`](https://rdrr.io/github/trinker/textreadr/man/read_odt.html) packages helpful for reading OpenOffice documents.


