---
title: "10x AI Hackathon"
format: html
date: 2024-04-15
---

Welcome to the event page for the 10X AI Hackathon, presented by the data science team of 10 Downing Street (10DS) in collaboration with [Imperial](https://www.imperial.ac.uk/) as part of the Evidence House program.

The hackathon will take place on the main campus of [Imperial College](https://maps.app.goo.gl/hmZz6u5vcx6X858k8), with doors opening from around 9am Monday (we will provide a more detailed schedule shortly).

Before you attend, [make sure you're ready to hit the ground running on day 1!](getting-ready.qmd)

## Key Challenges
How could we use AI to...

1. [**Ministerial Correspondence :**](challenges/correspondence/correspondence.qmd) Understand and respond to the most critical correspondence?
2. [**Emerging Situations and Crises :**](challenges/situations/situations.qmd) Identify, analyse and manage emerging crises and situations?
3. [**Legislation :**](challenges/legislation/legislation.qmd) Write better legislation, with better evidence, that's better understood?
4. **Communications :**  Communicate and understand the public, and help the public communicate with government?
5. **Meetings and Transcription :** Understand how to safely use, deploy and test AI systems?
6. **Manage Major Projects :** Track, measure, manage major government projects to ensure they're delivered on time?
7. [**Grants and awards :**](challenges/grants/grants.qmd)  Improve how governmetn distributes grands and awards?
8. **Skills :** Make sure everyone is equipped with the skills and capabilities to make the most of the AI revolution?

## Teams
Each team will be randomly assigned 3 problems, and we'll be asking you to decide on one to focus your tool on at the end of day 1!

Expect more information in the next few days.

## Agenda (TBC)

## Datasets
We've prepared a selection of datasets for the event, and these can be viewed on our [datasets page.](data.qmd)

Where data has been pre-prepared, we have hosted it on a S3 bucket - we will provide access and details on the day of the hack.

## Tools and Resources (TBC)
